### ISSUE TITLE
快冲/doge

### ISSUE THREAD

**Issue by Geniucker** [cyc-987/my-crawler-acee#1]
😇

**Comment by Geniucker** [comment]
😇

**Comment by cyc-987** [comment]
上完课就冲🚀

**Comment by Geniucker** [comment]
我又来监工了🫢

**Comment by cyc-987** [comment]
雷普啊，我找了一晚上程序的问题然后发现b站每一页给的脚本内容是一样的

**Comment by Geniucker** [comment]
脚本内容当然是一样的，肯定是调用的参数什么的变了，根据我的观察，我猜测他是先浏览器发一个请求给api，拿到搜索结果，然后js解析玩再动页面Sent from Android device2023年3月22日 11:27，cycyc2333 ***@***.***>写道：
雷普啊，我找了一晚上程序的问题然后发现b站每一页给的脚本内容是一样的

**Comment by Geniucker** [comment]
所以我写的那个方案就是直接去问api要结果

**Comment by Geniucker** [comment]
b站是懂反爬的，分两次请求才有最后界面，防止你第一次get就能拿到搜索结果

**Comment by cyc-987** [comment]
我觉得是因为b站在加载第二页及以后的搜索页面是用了异步请求，直接请求api就行了，但是要带cookies否则会返回412，然后params不需要很多，都可以拿掉，只留下几个

**Comment by cyc-987** [comment]
我指的那个script里面貌似是一页的内容，但是又不是json，我用re搞了好久。。。最后发现每一页都是一样的

**Comment by Geniucker** [comment]
他每一页只请求了当前页的结果，应该不是异步加载后面
细说是哪个script

**Comment by cyc-987** [comment]
清除cookies,访问https://search.bilibili.com/all?keyword=ikun&page=2&o=30
xpath：/html/body/script[2]
